### ISSUE TITLE
Certain parts come back as null

### ISSUE THREAD

**Issue by Nicron1557** [alfg/overwatch-api#108]
won/lost/draw and playtime all come back as null on several accounts I've tested and its breaking my program due to it being seen as undefined.

Example of broken api: http://owapi.io/profile/pc/ca/SkaterSeth-1551
![image](https://user-images.githubusercontent.com/86170690/160276112-1c194eff-92cc-487a-901d-edbc4eab8a0d.png)

**Comment by alfg** [comment]
Hey @Nicron1557, the account must not be private in order for all stats to show. 
https://playoverwatch.com/en-us/career/pc/SkaterSeth-1551/

This is noted in the readme since the June 26, 2018 patch:
https://github.com/alfg/overwatch-api#features
