### ISSUE TITLE
AUS Players not working?

### ISSUE THREAD

**Issue by axi92** [alfg/overwatch-api#109]
This profile is not working with the api.
https://playoverwatch.com/en-us/career/pc/CoachTeach-1352/
Any Ideas why?
What region is AUS?

**Comment by alfg** [comment]
Seems to resolve on:
https://owapi.io/profile/pc/us/CoachTeach-1352

**Comment by axi92** [comment]
Ah ok its case sensitive, did not know that.
Do you know how often blizzard updates those statistics when you are playing?

**Comment by alfg** [comment]
Not sure how often Blizzard updates, but I have my application set to refresh every 15mins.

**Comment by axi92** [comment]
Do you use a TSDB for that or what is your usecase?

**Comment by alfg** [comment]
Sorry, can you elaborate?

**Comment by axi92** [comment]
What is your usecase, what do you use your data for? I tried to make a chart (time based) so I can see when did what change over time.
And for that it would be interesting how often blizzard updates those values.
If it is only 2 times a day I dont need to scrap every 15 minutes =)

**Comment by alfg** [comment]
I don't currently use it for anything, just provided an API over the playoverwatch page for anyone to use. I only cache for 15mins and update as a request comes in for that player. I don't scrape the whole website every 15mins.

**Comment by axi92** [comment]
I figured it out, every time you close OW your stats get updated.
