### ISSUE TITLE
Overwatch 2 Player Profiles Released

### ISSUE THREAD

**Issue by InTheDaylight14** [alfg/overwatch-api#110]
The profile pages have changed with Overwatch 2. 

New url: https://overwatch.blizzard.com/en-us/career/PLAYER

**Comment by alfg** [comment]
Thanks. Will work on updating this soon.

**Comment by alfg** [comment]
@InTheDaylight14 This is fixed and deployed. Though many results are now removed as they are deprecated by OW2. 

From release notes:

> Updated parsers and hosts to support OW2 player pages. The following features have also been removed as they are not supported in the OW2 anymore:
> * Levels
> * Rank
> * Prestige Level
> * Endorsement stats (only level supported now).
> 
> Region and platform are no longer required. However, APIs will continue to support both to maintain compatibility.
>
