### ISSUE TITLE
Overwatch2 ranks available again

### ISSUE THREAD

**Issue by axi92** [alfg/overwatch-api#112]
https://overwatch.blizzard.com/en-us/career/axi92-2423/
Ranks are there again =)
![grafik](https://user-images.githubusercontent.com/1394837/219729849-85c48a41-44d8-4404-aebb-a2d1c31aca00.png)

**Comment by alfg** [comment]
Good to know! I'll look into adding these again. Thanks, @axi92!

**Comment by alfg** [comment]
Competitive ranks are added back!

![Capture](https://user-images.githubusercontent.com/702541/220294305-0575bab9-45e5-4527-9325-30ad32977ea5.PNG)

**Comment by alfg** [comment]
#113
