### ISSUE TITLE
[Feature Request] Ability to get only one value from the object from url

### ISSUE THREAD

**Issue by Ruben-Smit** [alfg/overwatch-api#13]
Hello,

I was trying to use your api with twitch's nightbot's commands but it has a 400 character limit.
Therefore I would like to have a way to get only 1 value in plain text by changing the url.
Right now I have worked around it by hosting my own website and getting the exact data from your api but I'd love to just get it directly.

Thanks for reading and thanks for the cool API

**Comment by alfg** [comment]
Hi @Rerbun, 

It sounds like you want to filter out certain properties from the response to minimize the character limit, correct? 

Would something like this work?
`http://ow-api.herokuapp.com/profile/pc/us/Alf-1608?include=username,games`

With a response:
```
{
    "username": "Alf",
    "games": {
        "quickplay": {
            "won": 508
        },
        "competitive": {
            "won": 26,
            "lost": 26,
            "draw": 2,
            "played": 54
        }
    }
}
```

If that sounds about right, just give me some time and I'll see what I can do.

Thanks!
-Alf

**Comment by alfg** [comment]
Hi @Rerbun, 

I just merged in https://github.com/alfg/overwatch-api/pull/14 with this feature. You should be able to make the request I mentioned above to filter out unwanted properties.

`http://ow-api.herokuapp.com/profile/pc/us/Alf-1608?include=username,games`

```json
{
    "username": "Alf",
    "games": {
        "quickplay": {
            "won": 1109
        },
        "competitive": {
            "won": 26,
            "lost": 26,
            "draw": 2,
            "played": 54
        }
    }
}
```

Let me know if this works for you.

**Comment by Ruben-Smit** [comment]
It's perfect! I've just tested it and works great. Thank you very much!
