### ISSUE TITLE
Querying a player with no Rank yields a truncated result

### ISSUE THREAD

**Issue by Ruthalas** [alfg/overwatch-api#18]
The array returned for a player who has yet to receive a rank is missing the entry for rank_img entirely, rather than having an entry marked null.

This makes the results inconsistently sized depending on whether a player has earned their rank or not.

Attached are the results for two players, one of whom is ranked for the current season and has 13 fields, while the player who has yet to rank only has 12 fields.

![01](https://user-images.githubusercontent.com/27835519/28847215-4a8c1302-76c3-11e7-9641-e3a4a9d6f892.png)

Ideally the returned array for both players would be the same length, with a placeholder for players with no rank, as is the case in "rank=null" or "draw=0".

(Thanks for this tool by the way! People like you make the world go 'round!)

**Comment by alfg** [comment]
Hi @Ruthalas!

Thanks for the suggestion. I'll look into adding a default `null` to `rank_img` later tonight!

-Alf

**Comment by alfg** [comment]
Hi @Ruthalas, 

This is fixed. https://github.com/alfg/overwatch-api/pull/19

Thanks for reporting this. :)

**Comment by Ruthalas** [comment]
Thank you! 

Your work is much appreciated.
My friends and I love your API.
