### ISSUE TITLE
help needed - routing

### ISSUE THREAD

**Issue by richielo** [alfg/overwatch-api#20]
Thank you very much for developing this API. Hope this is not to improper to ask. I am trying to use this API just for practice and fun. I am very new to nodejs. I am trying to add a router to the code of this API but it's giving me bad request....
I have created a test.js file in the routes directory:

const express = require('express');
const router = express.Router();
router.get('/', (req, res) => {
    console.log("test request received");
});
export default router

I also added 2 lines to the index.js file in the app directory:
import test from './routes/test';
export default function(app) {
  app.use('/', index);
  app.use('/profile', profile);
  app.use('/stats', stats);
  app.use('/test', test);
  app.use('*', badRequest);
}

May I ask for some help on why am I getting bad request? I probably have not changed something important. Thanks a lot in advance.

**Comment by alfg** [comment]
Hi @richielo, 

In your router.get, try adding the callback `res.json({ test: "test" );`

**Comment by richielo** [comment]
Hi @alfg thanks a lot for your help , I tried that but it's still not working, are there any other places I may have to change too?

**Comment by richielo** [comment]
i added this line res.json({ test: "test"}) and it just goes straight to bad request..

**Comment by alfg** [comment]
Hmm, strange. I just tried testing locally and I'm getting a response.

`app/routes/test.js`
```javascript
const express = require('express');
const router = express.Router();

router.get('/', (req, res) => {
    res.json({ test: "test" });
});

export default router;
```

`app/index.js`
```javascript
import index from './routes/index';
import profile from './routes/profile';
import stats from './routes/stats';
import badRequest from './routes/badRequest';
import test from './routes/test';

export default function(app) {
  app.use('/', index);
  app.use('/profile', profile);
  app.use('/stats', stats);
  app.use('/test', test);
  app.use('*', badRequest);
}
```

```
curl http://localhost:3000/test
HTTP/1.1 200 OK
Content-Type: application/json; charset=utf-8
Content-Length: 15
{"test":"test"}
```

**Comment by richielo** [comment]
....I found that I made a very simple syntax error, thank you so much for your help

**Comment by alfg** [comment]
No problem! Glad you figured it out. :)
