### ISSUE TITLE
Rank returning null

### ISSUE THREAD

**Issue by P-L-K** [alfg/overwatch-api#23]
See example:

http://ow-api.herokuapp.com/profile/pc/us/GunBlade-1949

`{"username":"GunBlade","level":954,"portrait":"https://d1u1mce87gyfbn.cloudfront.net/game/unlocks/0x0250000000000BBB.png","games":{"quickplay":{"won":2015},"competitive":{"won":241,"lost":246,"draw":11,"played":498}},"playtime":{"quickplay":"492 hours","competitive":"108 hours"},"competitive":{"rank":null,"rank_img":null},"levelFrame":"https://d1u1mce87gyfbn.cloudfront.net/game/playerlevelrewards/0x025000000000097C_Border.","star":"https://d1u1mce87gyfbn.cloudfront.net/game/playerlevelrewards/0x025000000000097C_Rank."}`

**Comment by alfg** [comment]
Hi @P-L-K, 

I see the rank and rank img resolving. Did you see it returning null during off season by any chance?
