### ISSUE TITLE
HI, can u add a level and avatar img in the profile response 

### ISSUE THREAD

**Issue by gabrielCortesReyes** [alfg/overwatch-api#3]
Hi, 

Thank you for your work.

I would appreciate it if you could add the player level and avatar image in the profile response.

**Comment by alfg** [comment]
Hi @gabrielCortesReyes,

I'll look into this soon!

**Comment by alfg** [comment]
This is done!

http://ow-api.herokuapp.com/profile/pc/us/spacecat-11681

Thanks!

**Comment by gabrielCortesReyes** [comment]
Thanks to u !!

2017-02-09 1:46 GMT-03:00 Alfred Gutierrez <notifications@github.com>:
