### ISSUE TITLE
API is down

### ISSUE THREAD

**Issue by EvHaus** [alfg/overwatch-api#32]
Looks like the API went down yesterday. The site is not accessible.

**Comment by alfg** [comment]
Hi @EvHaus, 

It seems like I’ve reached my free monthly quota from Heroku. :( 

I’ve upgraded my service plan and it should now be back in service. However, keep in mind as mentioned in the readme it is recommended to fork and run your own instance as the one I have hosted on Heroku is used for development and testing.

Thanks!

**Comment by EvHaus** [comment]
Thanks for the fast response. Appreciate it!
