### ISSUE TITLE
Feature Request: Allow installation via `npm` for use in NodeJS services

### ISSUE THREAD

**Issue by EvHaus** [alfg/overwatch-api#34]
Firstly, thanks for the amazing API.

I see that this package is already available via the `npm` registry and can be installed through `npm`. However, it looks like it's primarily optimized for running your own instance of the REST API server. I'm wondering if I could request the ability to install this package as an on-demand utility for making requests for OW stats instead. My use case is to use this package inside a Discord bot, so I have no need to run a standalone `srv` service with the API. I just need to make on-demand requests to the Overwatch stats from time to time.

My expectation is that I would be able to:

- `npm install overwatch-api`
- Then import it into NodeJS service as `import OverwatchAPI from 'overwatch-api'`
- Then use either the `profile` or `stats` parsers directly via
- `OverwatchAPI.profile('us',  'pc', 'sometag-123', (response) => { console.log(response); })`

However, at the moment there are a few issues preventing me from using this package this way:

- The package is written with ES6 modules and cannot be easily imported as needed above. In order for this to work, you'd need to add a prepublish script to generate CommonJS modules in the output before publishing the package on `npm`.
- There is no `index.js` file that exports all the available parser utility functions.
- The `main` and `module` keys in `package.json` aren't setup correctly

If you don't object to this, I'd be happy to create a pull request with the needed changes.

**Comment by alfg** [comment]
Hi @EvHaus, 

That is correct. This project is an http server for fetching stats from the playoverwatch.com player pages, and not to be used as a client library. 

I like the idea of providing both a server and client library, though. I think we can either build in a client module into this project in addition to running the server as an option. Or as a separate project that's just an http client interface to a hosted instance of this project.

Any thoughts?

**Comment by EvHaus** [comment]
I think two separate projects might be the cleanest. Then the server project would simply be a consumer of the client library (making it easy to test and confirm that the client library is properly exported).

However, it means more work for you as now you'll have to maintain two projects simultaneously. Unless you use something like `lerna` to do this from a single project.

My recommendation would be to use something like `lerna`. Keep 1 Github project, but export two separate `npm` modules.

**Comment by alfg** [comment]
Ah, that's cool. I never heard of lerna before. Thank you.

I like the approach of having two separate modules in one project.

**Comment by alfg** [comment]
Hi @EvHaus, 

I've added https://github.com/alfg/overwatch-api/pull/35 with the above request. 

I separated the server and overwatch api into separate package. The `overwatch-api` module is now just the API to utilize the 2 parser exports for getting profiles and stats. See the updated [README.md](https://github.com/alfg/overwatch-api/tree/master/api). This is also packaged via babel with prepublish.

The server is now just a standalone srv/express server importing the `overwatch-api` package.

Let me know any thoughts or suggestions! I checked out `lerna`, but chose not to use it for just two modules. It looks great for a monolith repo with many packages, though!

**Comment by EvHaus** [comment]
@alfg  I think you might need to change the `"main"` key in the root `package.json` to be "api/src/index.js". Otherwise you can't import it via `import api from 'overwatch-api'`

**Comment by alfg** [comment]
Hey @EvHaus,

Sorry for the late reply. If the `main` key in the root package.json refers to the server, does that still need to be updated? The api client has main the key set in `api/package.json`.

**Comment by EvHaus** [comment]
Currently, when you install `overwatch-api`, it installs the main `package.json`. So if that points to the server, then it's not possible to use this package as intended.

If you want to use the `api/package.json` for that purpose, then you would need to publish two separate packages. First, publish the main server from `/package.json` and then publish the api from `api/package.json` with a completely different npm package name.

Hope that helps.

**Comment by alfg** [comment]
Right, currently I'm publishing the root as `overwatch-api-server`, and the client within `api/package.json` as `overwatch-api` to be the client api as two separate packages. Is that different from what you are saying?

**Comment by EvHaus** [comment]
Ah, my bad! I completely missed the new API docs. It works great. Thank you so much!
