### ISSUE TITLE
Add winrate for competitive mode

### ISSUE THREAD

**Issue by ghost** [alfg/overwatch-api#37]
f: round((wins / (games - ties)) * 100, 2)

so I would like to see detailed information for each hero

**Comment by alfg** [comment]
Hi @iAxel, 

Adding the winrate to profile/stats shouldn't be an issue, but I'm not so sure about for each hero? Do you know if this is displayed on the battle.net player site?

**Comment by alfg** [comment]
Ah, I just noticed the Overwatch player page shows the winrates for each hero. I'll look into adding this soon!

**Comment by alfg** [comment]
`win_rate` is now added to the profile endpoint under `games.competitive`.
`played`, `games_won` and `win_rate` are also added to the stats endpoint under `top_heroes`.

**Comment by ghost** [comment]
ty 👍
