### ISSUE TITLE
Hitting api returns an empty object

### ISSUE THREAD

**Issue by bencoullie** [alfg/overwatch-api#40]
When I hit the api with an account code I know exists, such as, `http://ow-api.herokuapp.com/profile/pc/us/VoA-1535` or `http://ow-api.herokuapp.com/profile/pc/us/cupchip-2806` I get an empty object response (no error or explanation).

This only happens sometimes. Other times it works fine with the same credentials. This only started happening a few days ago as far as I can tell. 

I can try another account (such as `http://ow-api.herokuapp.com/profile/pc/us/OctopusPrime-1324` and it works fine. It only seems to be happening to some accounts some of the time.

Any ideas? My initial thought is rate limiting (though I probably only hit it a few times a day). Do you have rate limiting set up per account by any chance?

**Comment by alfg** [comment]
Thanks for reporting. Checking into this!

**Comment by alfg** [comment]
The Overwatch player profile page seems to be returning no results right now as well:
https://playoverwatch.com/en-us/career/pc/VoA-1535

I don't have any rate limiting in place.

Unfortunately, I cannot parse the profile/stats until the Overwatch player page is resolving.

**Comment by alfg** [comment]
Most of the api calls right now are returning the same results. We'll probably have to wait until the overwatch page issues are resolved.

**Comment by alfg** [comment]
Seems to be working again.

**Comment by bencoullie** [comment]
Thanks for looking into this! I appreciate it.

Yeah I see, it seems to be official blizzard site issues. 

Its still occurring for me: I'm getting a `503` service unavailable when I hit your API and when I try visit the page manually (`503: CloudFront attempted to establish a connection with the origin, but either the attempt failed or the origin closed the connection.`).

🤞 they fix their shit. I'll keep checking in in the hopes it gets going again.

**Comment by alfg** [comment]
Yeah, hopefully they resolve their issues soon. I noticed other similar overwatch projects are experiencing issues as well.
