### ISSUE TITLE
Clean up API/API documentation

### ISSUE THREAD

**Issue by JoshuaHall** [alfg/overwatch-api#41]
Hey, I was looking at the overwatch-api npm package's [documentation](https://github.com/alfg/overwatch-api/blob/master/api/README.md) and I saw that the callback supposedly takes two arguments, `err` and `data`, where `err` contains error info and `data` is the response from the server, but as far as I can tell the second argument data is never actually used, and the first argument is used for both. I'm currently in the process of making a TypeScript types declaration file for the overwatch-api package so it would be helpful if you could either fix this or point me in the right direction for how the package works, thanks!

P.S. I really appreciate the work you've done on this package, nice to not have to manually figure this out myself 👍

**Comment by alfg** [comment]
Oh wow. Nice catch! 

Yes, I should be returning `null` for err when there's a response. I'll fix and update soon!

Thanks for reporting this! :)

**Comment by alfg** [comment]
Hi @JoshuaHall, 

This is updated with #42, deployed, and published to npm. Let me know if this works for you!

Thanks.

**Comment by JoshuaHall** [comment]
Yeah, the API works as expected for me now, thanks!

**Comment by alfg** [comment]
Great, thanks! Would love to see the TypeScript types when those are ready. :)

**Comment by JoshuaHall** [comment]
Here are the [completed TypeScript types](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/ff6e2a603e1553bb99c3b934407cd7544d0a2b6b/types/overwatch-api), it isn't available by doing `npm install @types/overwatch-api` or `yarn add @types/overwatch-api` just yet but the bot that they have to automatically add types should do that soon :) Let me know if you have any feedback, this is my first type declaration file of any meaningful size.

**Comment by alfg** [comment]
Awesome. Looks good! Thanks!
