### ISSUE TITLE
[Feature Request] All Top Heroes stats

### ISSUE THREAD

**Issue by Shadorc** [alfg/overwatch-api#51]
Hello, 
it would be nice to have access to each Top Heroes stats.
I don't know if there is a reason for this but we can only get "Time Played" and "Games Won" stats.

Sadly, I can't make a pull request and test it for now but here are the overwatch.guid values for each category (if it can help) ;

Weapon Accuracy: 0x086000000000002F
Eliminations per Life: 0x08600000000003D2
Multikill - Best: 0x0860000000000346
Objective Kills - Average: 0x086000000000039C

Thanks for this amazing API !

**Comment by alfg** [comment]
Thanks @Shadorc. I'll look into this tonight.

**Comment by alfg** [comment]
Hi @Shadorc,

I'm not seeing the Weapon Accuracy stat on the playoverwatch page. Can you post an example?
I'm looking at https://playoverwatch.com/en-us/career/pc/xQc-11273.

I see Multikill and Objective Kills showing up on the overwatch-api, but not the other 2. I could be missing something though!

**Comment by alfg** [comment]
Ah! I see it now. I missed the dropdown filters. I'll work on this soon!

**Comment by alfg** [comment]
Hi @Shadorc, 

I added the changes on https://github.com/alfg/overwatch-api/pull/52.

The API is updated and npm packages are published! Let me know if this works for you.

Thanks!

**Comment by Shadorc** [comment]
Thanks !
It was quick
