### ISSUE TITLE
Searching names with simbol Ƕ

### ISSUE THREAD

**Issue by Simego** [alfg/overwatch-api#6]
I'm testing your API and liking it so far compared to many others, the only problem i found was when the battletag has the simbol Ƕ (the one people use to make the nickname big) and i haven't found a way to fix it

**Comment by alfg** [comment]
Hi @Simego. Thanks for checking it out!

Do you have an example of a character posting using the Ƕ symbol on the overwatch community site? https://playoverwatch.com/en-us/community/

I'm guessing it might just be an encoding fix.

**Comment by Simego** [comment]
Yeah i think it is encoding..
https://playoverwatch.com/en-us/search?q=HINO%C7%B6-1257
https://www.overbuff.com/players/pc/HINO%C7%B6-1257

**Comment by alfg** [comment]
Should be fixed!

http://ow-api.herokuapp.com/profile/pc/us/HINO%C7%B6-1257
