### ISSUE TITLE
support ow cn

### ISSUE THREAD

**Issue by NeonCowboy** [alfg/overwatch-api#62]
I have try to GET http://ow-api.herokuapp.com/profile/pc/cn/MegaAthy-5469
But I can only get {}
So I am wondering if this api support cnow now.

**Comment by alfg** [comment]
Hi @JohnnyWang94, 

Do you have a link to the playoverwatch player page? It doesn't seem to come up on https://playoverwatch.com/en-us/search?q=MegaAthy-5469.

Unless there's a separate url for CN.

**Comment by NeonCowboy** [comment]
生田絵梨花-51323
I have tried to search on this site, but still can not get the player's information.

**Comment by alfg** [comment]
OK, if someone is able to find the profile site for CN, then I should be able to parse it.

**Comment by Shadorc** [comment]
It seems like a different endpoint for CN, other APIs have this problem too (https://github.com/Fuyukai/OWAPI/issues/9)
I did not find it, but Master Overwatch did apparently.
For example: https://masteroverwatch.com/profile/pc/cn/Song-5702 exists but https://playoverwatch.com/en-us/career/pc/Song-5702 does not.

**Comment by alfg** [comment]
Thanks for the info @Shadorc. I wonder how Master Overwatch is doing it. 🤔
