### ISSUE TITLE
When profile doesn't exist, receive "Callback was already called."

### ISSUE THREAD

**Issue by deriven** [alfg/overwatch-api#63]
To reproduce, use either getProfile() or getStats() with a tag that doesn't exist.  The issue is that the parseHTML and getHTML functions are both trying to callback() an error for the same reason.

I solved this by removing the catch in the getHTML.  Let the catch bubble up instead.

**Comment by alfg** [comment]
Hi @deriven,

I'm not able to reproduce the `Callback was already called` message. Can you post a snippet I can use as an example? Also, are you using this as a server, or the overwatch-api npm package?

**Comment by alfg** [comment]
I also just added https://github.com/alfg/overwatch-api/commit/34a88fbb248408c2406ae8d5eb8784d153e55df5 to master, but it's not published yet.

**Comment by deriven** [comment]
I pulled the latest and tested -- didn't get the issue.  Also ran the npm package and no issue.  However I know why I got the issue.  Both the source and the npm package do not have the async package.  And I believe my version of async in my project was old or something.  The latest async may not show the error.  If I recall, there was an issue on async's github where it doesn't do it anymore or inappropriately.

Anyway, the REAL problem is that both the src and the npm package do not include async.  To reproduce:

1. Pull latest
2. Go to api/ and `npm install && npm run compile`
3. Type `node` and run the following
`var owapi = require('./lib')`

You should receive the error...
```Error: Cannot find module 'async'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
```
  
Same thing happens if you create a new project (`npm init`) and install the overwatch-api solely.  Then try to use it in a node prompt.  If I manually `npm install async` it works.

**Comment by alfg** [comment]
Ah, that makes sense. I must have forgotten to include async from one of my last PRs, and instead I probably already had it installed. Good catch. I will fix shortly.

**Comment by alfg** [comment]
`async` added to dependencies on https://github.com/alfg/overwatch-api/commit/3a8dea1473d2d5111f877c013d074a093be93548.

Thanks!
