### ISSUE TITLE
Use NPM Module: Cross-domain Error

### ISSUE THREAD

**Issue by AkiyamaMinami** [alfg/overwatch-api#66]
Sorry to trouble you, when I use the JS API based on document Example in my project for the test, I got a Cross-domain problem error...I don't know how to solve it.
![image](https://user-images.githubusercontent.com/31888190/51729786-1b8bf200-20b0-11e9-8d02-0bd7e226c465.png)

**Comment by alfg** [comment]
Hi @AkiyamaMinami, 

Since the NPM module makes an external xhr request to the playoverwatch.com website to scrape the results, it can only be used as a node module and not through the browser. Unless Blizzard allows, the cross-origin rules will block any JS requests from being made. :(

**Comment by alfg** [comment]
I would suggest making the API call from the backend/node, and serve the json response to your client/browser frontend. This way you have control over the cross-origin rules.

**Comment by AkiyamaMinami** [comment]
@alfg Thank you for your explanation, and I follow your suggestion and call API at Node successfully! thank you very much~ 233

**Comment by antoinegilles** [comment]
hello,
Can you explain the solution please. I use your API with just a front-end to see the values of the players. How can i resolve this problem ?

**Comment by antoinegilles** [comment]
i use react js for information

**Comment by alfg** [comment]
Hi @antoinegilles, 

You will need to make the request from the backend and serve it to your client to address the CORS issue. This way your frontend client is making a request on the same domain.

https://enable-cors.org/server_expressjs.html

For example, an express.js `server.js` would look something like:
```javascript
app.use(function(req, res, next) {
  res.header("Access-Control-Allow-Origin", "*");
  res.header("Access-Control-Allow-Headers", "Origin, X-Requested-With, Content-Type, Accept");
  next();
});

app.get('/api', function(req, res, next) {
  // Make overwatch-api request here.
  const platform = 'pc';
  const region = 'us';
  const tag = 'Calvin-1337';

  overwatch.getProfile(platform, region, tag, (err, json) => {
    if (err) console.error(err);
    return res.json(json);
  });
});
```

Then on your react client, you can just call your `/api` endpoint instead of using a regular http request.

**Comment by antoinegilles** [comment]
Hello @alfg 
Thank's for the answers. I realise a little back-end in Node JS to use your API. here is the links of my repo : https://github.com/antoinegilles/backDashboardOverwatch if maybe you want to star it or follow me.
antoine Gilles

**Comment by alfg** [comment]
Looks good @antoinegilles! Will keep an eye on it to see it in action!

**Comment by antoinegilles** [comment]
Thanks for now i dont deploy it yet i will tell you when it s ready

**Comment by antoinegilles** [comment]
But it work in local

**Comment by antoinegilles** [comment]
hey @alfg  
I come back to you to show your my final Front-end project. Here is the link of my repo there is the link for the website. If your like you can start it :) https://github.com/antoinegilles/dashboardOverwatch/blob/master/README.md
