### ISSUE TITLE
Role queue stats missing

### ISSUE THREAD

**Issue by alfg** [alfg/overwatch-api#72]
Latest Travis builds are failing due to role queue stats missing:
```json
  "competitive": {
    "tank": {
      "rank": null,
      "rank_img": null
    },
    "damage": {
      "rank": null,
      "rank_img": null
    },
    "support": {
      "rank": null,
      "rank_img": null
    }
  },
```

I no longer see the Role Queue stats on the playoverwatch.com page:
https://playoverwatch.com/en-us/career/pc/xQc-11273

The parser can't find the DOM elements:
```
$('.competitive-rank div[data-ow-tooltip-text="Tank Skill Rating"] img').attr('src') || null;
$('.competitive-rank div[data-ow-tooltip-text="Damage Skill Rating"] img').attr('src') || null;
$('.competitive-rank div[data-ow-tooltip-text="Support Skill Rating"] img').attr('src') || null;
$('.competitive-rank div[data-ow-tooltip-text="Tank Skill Rating"]').next().html();
$('.competitive-rank div[data-ow-tooltip-text="Damage Skill Rating"]').next().html();
$('.competitive-rank div[data-ow-tooltip-text="Support Skill Rating"]').next().html();
```

Did Blizzard change something around Role Queue? Any input would be appreciated.

Thanks!

**Comment by filp** [comment]
I can only assume Blizzard is working on this alongside the Role Queue beta, and will be updating profiles to match at some point. Even in-game there's a lot of inconsistency in how stats are displayed, where relating to role-based skill.

Ran into this issue while investigating options for fixing my own API client, and so far there doesn't appear to be any solution.

**Comment by alfg** [comment]
Thanks for the input @filp. I haven't played in a while, so I haven't been keeping up with some of the latest updates. Appreciate the info!

**Comment by alfg** [comment]
Seems to be working again and the Travis build are passing. Will re-open if it comes back up.
