### ISSUE TITLE
Application Error

### ISSUE THREAD

**Issue by Shadorc** [alfg/overwatch-api#75]
Hi, 
recently the API started throwing 404 on every requests.
For example: https://ow-api.herokuapp.com/stats/pc/eu/Shadorc-2503

**Comment by alfg** [comment]
Hi @Shadorc, 

The updated domain is now https://owapi.io.

Try:
https://owapi.io/stats/pc/eu/Shadorc-2503

**Comment by Shadorc** [comment]
Oh sorry, I didn't updated the domain URL, thanks !
