### ISSUE TITLE
Add overwatch arcade title

### ISSUE THREAD

**Issue by dansleboby** [alfg/overwatch-api#76]
In title

**Comment by alfg** [comment]
Can you explain what the arcade title is? And if possible a link or example on the playoverwatch website?

I haven't been staying up to date on Overwatch lately.

**Comment by dansleboby** [comment]
https://overwatcharcade.today/

https://overwatcharcade.today/api/today

https://overwatcharcade.today/api/gamemodes

**Comment by alfg** [comment]
It's a pretty cool website, but out of scope for this project. Thanks for the suggestion, though!

Is it open source? I couldn't find a Github link on their website.
