### ISSUE TITLE
Support Nintendo Switch for NPM Package

### ISSUE THREAD

**Issue by addidotlol** [alfg/overwatch-api#77]
OW for Nintendo Switch just came out, so there should be support for Nintendo Switch in the NPM package.

**Comment by alfg** [comment]
Thanks for the heads up. I'll look into adding this soon!

**Comment by alfg** [comment]
So it seems you can already use `nintendo-switch` as the platform, and the also plug in the username:
https://api.owapi.io/profile/nintendo-switch/us/KRUSHER99-8203f14ccb7628fa52851ee40a04c216

The above is just a private account I searched, so it doesn't display all the details. But it should work for the NPM package too.

I'll look into updating the docs too.
