### ISSUE TITLE
Regarding Player "Star" URLs

### ISSUE THREAD

**Issue by Ruthalas** [alfg/overwatch-api#8]
Hey guys! Apologies if this is the incorrect channel to ask about this, but I have a question about the "star" data returned by your API.

From a quick look at your code, it looks like the urls you are returning are directly pulled from playoverwatch. Have you noticed any pattern in the star URLs?

There appear to be many alternate images for each level of stars.
One bronze star, for example, can be represented by any of the following URLs, among many others:
https://blzgdapipro-a.akamaihd.net/game/playerlevelrewards/0x0250000000000924_Rank.png
https://blzgdapipro-a.akamaihd.net/game/playerlevelrewards/0x0250000000000925_Rank.png
https://blzgdapipro-a.akamaihd.net/game/playerlevelrewards/0x0250000000000926_Rank.png
https://blzgdapipro-a.akamaihd.net/game/playerlevelrewards/0x0250000000000927_Rank.png
https://blzgdapipro-a.akamaihd.net/game/playerlevelrewards/0x0250000000000928_Rank.png

This makes parsing the total level (prestige/stars + "level") a difficult task.
(Currently I have a list of many of the URLs and their associated star-count in a look-up table, but this is inelegant.)

Do you happen to know of any pattern or trick for discerning the appropriate star-count from these urls?

Regardless, thanks for providing this tool!
It has been a pleasure to incorporate into my groups tracking spreadsheet.

**Comment by alfg** [comment]
Hi @Ruthalas, 

Correct, we just pull the image url from the scraped content from the playoverwatch page.

It seems the naming conventions for the filenames are in hexidecimal, starting with 
`0x0250000000000922`, which is basically hex for `02800000934`, or just `934` if you use only the last 2 bytes.

So it seems they are in incremental order. For example:
```
0x0250000000000922 - 934
0x0250000000000923 - 935
0x0250000000000924 - 936
0x0250000000000925 - 937
...
0x02500000000009CC - 9204
0x02500000000009CD - 9205
```

I'm not too sure how the decimal number correlates to the stars/rank, though.

It  might still be best to create a map similar to:
https://github.com/SunDwarf/OWAPI/blob/master/owapi/prestige.py

If you anything, I'd like to know as well! :)
