### ISSUE TITLE
💬 Report owapi.io API Status issues here

### ISSUE THREAD

**Issue by alfg** [alfg/overwatch-api#82]
Please report here if you run into any issues on the hosted API at: https://owapi.io

**Comment by Shadorc** [comment]
The API seems down right now, returning "Application error": http://ow-api.herokuapp.com/

**Comment by alfg** [comment]
Hi @Shadorc,

That host is no longer in use, please try: https://owapi.io/

**Comment by Shadorc** [comment]
Oh sorry, I forgot. The API was sometimes returning JSON with all fields to null so I checked the first url on the doc' page and it was this linked, I forgot that this is now outdated.

**Comment by alfg** [comment]
@Shadorc Ah, good point. I gotta update the hostname on the docs.

Edit: Docs are now updated.

**Comment by Shadorc** [comment]
Blizzard seems to have updated its HTML, all fields are now null/empty: https://owapi.io/profile/pc/eu/shadorc-2503

**Comment by Shadorc** [comment]
Hello,
The API seems down: http://owapi.io/profile/pc/us/Jay3-11118, all fields are empty or null

**Comment by alfg** [comment]
Hey @Shadorc,

Thanks for the report. I flushed the cache and it seems to be getting results again. There may have been some timeouts.

**Comment by Shadorc** [comment]
Thank you for your quick response!

**Comment by Shadorc** [comment]
Hello, 
I'm encountering the same issue, all fields null or empty http://owapi.io/profile/pc/us/Jay3-11118

**Comment by alfg** [comment]
Hey @Shadorc, 

It seems to be responding with data again. Most likely a timeout on playoverwatch.com again and results were cached for a bit.

**Comment by Shadorc** [comment]
How long are the cached values kept?
Would it be possible to do something like, keep the value in cache, and when refreshing, do not update the last value if it contains only null or empty fields?

**Comment by alfg** [comment]
I currently have it set for a TTL of 30min (due to Blizzards rate limiting).

I added a retry mechanism a while back to not cache the results if the parse fails. However, there's probably something I missed in the event of a timeout or non-200 response. I'll check into it again soon.

**Comment by bhgr216** [comment]
> Hello,
> I'm encountering the same issue, all fields null or empty http://owapi.io/profile/pc/us/Jay3-11118

It seems to be down again.

**Comment by Shadorc** [comment]
It has been for a few days now

**Comment by alfg** [comment]
Thanks for reporting. Should be back up now. It was blocked again by Blizzard/PlayOverwatch.com.

**Comment by CornellFL** [comment]
Hello, I don't think that the API is working properly. It keeps saying {"message":"Error: Profile not found"} even for the sample url: http://owapi.io/profile/pc/us/Jay3-11118

I am new to programming so it could just be me.

**Comment by alfg** [comment]
Hi @Zoltixx, 

Yeah, the tests are failing because the Jay3 account seems to give a `Profile not found` now. I'm not sure why it changed, but I need to update to use another active account for testing.

https://playoverwatch.com/en-us/career/pc/Jay3-11118/ -> Profile Not Found

Other accounts seem to work fine:
https://owapi.io/profile/pc/us/xQc-11273

**Comment by CornellFL** [comment]
> Hi @Zoltixx,
> 
> Yeah, the tests are failing because the Jay3 account seems to give a `Profile not found` now. I'm not sure why it changed, but I need to update to use another active account for testing.
> 
> https://playoverwatch.com/en-us/career/pc/Jay3-11118/ -> Profile Not Found
> 
> Other accounts seem to work fine:
> https://owapi.io/profile/pc/us/xQc-11273

I just realized that the usernames are case sensitive, I got it to recognize my account. Thanks.
