### ISSUE TITLE
All information and stats missing in profile response

### ISSUE THREAD

**Issue by saitho** [alfg/overwatch-api#84]
I just checked the response of the API request for my profile.

https://owapi.io/profile/pc/eu/saitho-2703

Seems like the stats are missing. I'm especially looking for the quickplay time (see https://github.com/bartok765/galaxy_blizzard_plugin/issues/21).

Other information such as username and level are also empty.

**Comment by alfg** [comment]
Thanks @saitho. Checking into this.

**Comment by alfg** [comment]
Should be good now. Thanks!

**Comment by WilsonCazarre** [comment]
That issue it's still happening sometimes, but it doesn't seem to have a pattern.
Yesterday I was trying to get my profile and all the info was returned as `null`. Later, it started to return the correct info again, but my friend's profile went `null`.

Today both profiles are working.
Is there anything that you can say about that issue? What is causing it and why it feels like it's random?

**Comment by alfg** [comment]
Hi @WilsonCazarre, 

Unfortunately, I've been getting hit by rate limits on https://playoverwatch.com lately. I had to increase caching to 30mins to help mitigate the issue, but it's not 100% effective.

My guess is when a profile comes back as `null`, it was hit by a rate limit, and the `null` results are cached. I'll add a fix soon to prevent caching the results if the profile is `null` from the rate limit block, so the user can retry. I'll see if I can also add some retry mechanism as well.

Re-opening for now.

**Comment by alfg** [comment]
Updated to prevent caching profiles with `null` results and added a retry mechanism when fetching player data from playoverwatch.com.

#90 

I also skimmed through the cached entries and don't see any profiles with `null` results so far. However, as I mentioned before, it is still susceptible to the rate limiting issue.

Let me know if you still run into the issue. Thanks!

Note: Will be publishing the NPM packages shortly.
