### ISSUE TITLE
Level doesn't factor in stars

### ISSUE THREAD

**Issue by phillip-elm** [alfg/overwatch-api#9]
My account is level 255, but the API returns level 55. I suspect this is because the official overwatch page shows 55 and has long numeric filenames for the stars under the portrait. 

masteroverwatch.com shows the right value, so it looks like they've figured this out.

**Comment by alfg** [comment]
Hi @phillip-elm, 

Thanks for reporting this. I've been procrastinating on fixing this for a while now, but it's now fixed as part of https://github.com/alfg/overwatch-api/pull/10! :)

Feel free to report back if you experience any issues.

Thanks!
-Alf

**Comment by phillip-elm** [comment]
Thanks for the quick fix, @alfg - good stuff! :smile:
