### ISSUE TITLE
global region does not work

### ISSUE THREAD

**Issue by Shadorc** [alfg/overwatch-api#94]
Hello,
It seems that the `global` region no longer work.
https://owapi.io/profile/pc/eu/Shadorc-2503 works but not https://owapi.io/profile/pc/global/Shadorc-2503

**Comment by alfg** [comment]
Hi @Shadorc,

I'm checking https://owapi.io/profile/pc/global/Shadorc-2503 and it seems to load. Can you check again?

**Comment by Shadorc** [comment]
It now works... All the fields were null or empty and I could reproduce consistently.. mmh

**Comment by alfg** [comment]
Ah, might have been a hiccup on Blizzard's PlayOverwatch page, and results got cached.
